"""Constants for the Dimsome integration."""

DOMAIN = "dimsome"
VERSION = "0.3.1"
PLATFORMS = ["button", "sensor", "switch"]

SERVICE_RESUME = "resume"

CONF_LIGHTS = "lights"
CONF_GLOBAL = "global"
CONF_ENTITY_ID = "entity_id"
CONF_ENABLED = "enabled"
CONF_MIN_BRIGHTNESS_PCT = "min_brightness_pct"
CONF_MAX_BRIGHTNESS_PCT = "max_brightness_pct"
CONF_MIN_COLOR = "min_color"
CONF_MAX_COLOR = "max_color"
CONF_DIM_SCHEDULE = "dim_schedule"
CONF_BRIGHTEN_SCHEDULE = "brighten_schedule"
CONF_RAMP_DURATION = "ramp_duration"
CONF_OVERRIDE_RESUME_MODE = "override_resume_mode"
CONF_OVERRIDE_GRACE_PERIOD = "override_grace_period"
CONF_SPLIT_TURN_ON_CALLS = "split_turn_on_calls"
CONF_APPLY_ON_RECOVERED_ON = "apply_on_recovered_on"
CONF_SETTLE_DELAY = "settle_delay"
CONF_NATIVE_USER_IDS = "native_user_ids"
